import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "cprg306-assingments",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <body className="min-h-full flex flex-col">{children}</body>
  );
}
